[package]
name = "rusty-runner-api"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "rusty-runner-server",
]

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.91"
