[package]
name = "rusty-runner-server"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.0"
actix-files = "0.6.2"
env_logger = "0.10.0"
log = "0.4.17"
serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "1.24.2", features = ["process"] }
rusty-runner-api = { version = "1.0.0", path = "../" }
rand = "0.8.5"
