[package]
name = "rusty-runner-server"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty-runner-api = { version = "1", path = "../" }
# -- Async
tokio = { version = "1", features = ["fs", "process"] }
# -- Serde
serde = { version = "1", features = ["derive"]}
# -- Web
axum = "0.7"
tower-http = {version = "0.5", features = ["fs", "trace"] }
# -- Logging
log = { version = "0.4", features = ["kv"] }
env_logger = { version = "0.11", features = ["unstable-kv"] }
# -- Util
rand = "0.8"