[package]
name = "rusty-runner-server"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4"
actix-files = "0.6"
env_logger = "0.10"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.35", features = ["process"] }
rusty-runner-api = { version = "1.0", path = "../" }
rand = "0.8"
